"""
Django settings for password_generator project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# --------Shows, where on your computer your project is (BETTER NOT TO CHANGE)----------
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# --------Used when there is DATA FLOW in and out of your Website, can be changed anytime----------
# --------once our project is launches, this SECRET KEY should not be shared for Security
SECRET_KEY = 'django-insecure-^sf7h+1)zm3oo90-0f%hcpt!5vnt(0chy^)$64amk+4q&(2jly'

# SECURITY WARNING: don't run with debug turned on in production!
# --------DEBUG MODE (True/ False)---------> allows us to get detailed info of the BUG, the ERROR is displayed on the Webpage in Details.
# --------Should be True in DEV environment, False in Production
DEBUG = True


# --------Add the IP address of allowed Host when 'DEBUG = False', 'ALLOWED_HOSTS = ['localhost']' 
ALLOWED_HOSTS = []


# Application definition
# --------Way to bring different pieces of CODE into your Project
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'generator',
]


# ---------Built-in Django related things, USUALLY NOT CHANGED
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



# ---------Asks the LOCATION of urls.py file
ROOT_URLCONF = 'password_generator.urls'



# ---------Helps us in returning a customized HTML CODE, 
# The purpose of all WEB SERVER's, is to RETURN some HTML code for a given webpage
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# ---------Used in DEPLOYING the application
WSGI_APPLICATION = 'password_generator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# 'NAME': BASE_DIR / 'db.sqlite3', ---------> used for naming the DB, EX: 'eggs.sqlite3'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
# Used to specify the PASSWORD LIMITATIONS,
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# -------Website Content related Info, ex: language, timezone,..
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# --------Managing STATIC FILES in the Webpage
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
